package ar.edu.unlam.pb2.saladecine;

public enum NumeroDeButacas {
UNO, DOS, TRES, CUATRO, CINCO, SEIS, SIETE, OCHO, NUEVE, DIEZ, ONCE, DOCE, TRECE, CATORCE, QUINCE, DIECISEIS, DIECISIETE, DIECIOCHO, DIECINUEVO, VEINTE, VEINTIUNO
}
